glob_matcher: doublestar

pre-commit:
  parallel: false
  skip:
    - rebase

  commands:
    stylua-format:
      glob: '**/*.lua'
      run: stylua {staged_files}
      stage_fixed: true

    prettier-format:
      glob: '**/*.{js,jsx,ts,tsx,json,css,scss,md,yaml,yml}'
      run: |
        echo "Formatting files with prettier..."
        npx prettier --write {staged_files}
      stage_fixed: true

    record-demo-gif:
      glob: '**/*.lua'
      run: ./vhs/record-demo-gif.sh
